version: '3.7'
services:
  workscreen:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workscreen
    tty: true
    ports:
      - "4200:4200"
    volumes:
      - ../:/app
      - node_modules:/app/node_modules
volumes:
  node_modules:
      